name: getxauth
version: 1.0.0+1
publish_to: none
description: getXfire + middleware
environment: 
  sdk: '>=2.15.0-116.0.dev <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.5
  get: ^4.6.5
  awesome_notifications: ^0.7.4+1
  firebase_core: 2.4.1
  firebase_auth: 4.2.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

